name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install --frozen-lockfile
      - run: npm run package
      - run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
